[tool.commitizen]
name = "cz_kpn"
version_provider = "pep621"
version_files = [
    "scripts/build",
    "CONTRIBUTING.md",
    "Dockerfile:cz-kpn==",
    "README.md:^docker"
]
bump_message = "BUMP: version $current_version â†’ $new_version"
commit_url = "https://github.com/kpn/cz-kpn/commit/$COMMIT_REV"
update_changelog_on_bump = true
